server:
  port: ${serverPort:80}
  tomcat:
    basedir: ${serverTomcatBasedir:spring-tomcat/${spring.application.name}}

swagger:
  host: ${swaggerHost:}
  enabled: ${swaggerEnable:true}

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      read-timeout: 120000
      logger-level: ${feignClientConfigLoggerLevel:debug}
  url:
    mail-server: ${feignUrlMaiServer:http://cloud.hnlat.local/mail-server}
    fs-server: ${feignUrlFsServer:http://cloud.hnlat.com/fs-server}
    uo-server: ${feignUrlUoServer:http://cloud.hnlat.local/uo-server}
    pdfsearch-server: ${feignUrlPdfsearchServer:http://cloud.hnlat.local/pdfsearch-server}
######################################################################

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    database: MYSQL
    show-sql: ${springJpaShowSql:true}
    hibernate:
      ddl-auto: ${springJpaHibernateDDLAuto:update}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://${dbUrl:mysql-dev.database:3306}/${dbName:${spring.application.name}}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${dbUser:root}
    password: ${dbPass:wdkj@123#}
    druid:
      # 配置初始化大小、最小、最大
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: "select 1"
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置获取连接等待超时的时间
      max-wait: 60000
      async-init: true
      filters: stat,wall,slf4j
      aop-patterns:
        - com.wd.cloud.docdelivery.service.*
        - com.wd.cloud.docdelivery.repository.*
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin@123
  freemarker:
    template-loader-path: ["file:/app/templates/","classpath:/templates"]
    settings:
      classic_compatible: true
global:
  cloud-host: ${globalCloudHost:http://cloud.hnlat.local}
  hbase-table-name: literature
  file-types: [pdf,txt,doc,docx,zip,rar,caj]
  business: doc-delivery:result
cas:
  server-url-prefix: ${casServerUrlPrefix:http://sso.hnlat.local}
  server-login-url: ${casServerLoginUrl:http://sso.hnlat.local/login}
  server-validation-url: ${casServerValidationUrl:http://sso}
  client-host-url: ${casClientHostUrl:http://cloud.hnlat.local/doc-delivery}
  authentication-url-patterns: /*
  logout-url-patterns: /*
  validation-url-patterns: /*
  request-wrapper-url-patterns: /*