server:
  tomcat:
    basedir: ${basedir:/home/cloud/spring-tomcat/${spring.application.name}}
  port: ${port:10012}
  servlet:
    context-path: /
swagger:
  title: 文献传递服务-测试环境
  description: 文献传递服务API
  version: 2.0
  enabled: true
  contact:
    name: hezhigang
    email: hezhigang@hnwdkj.com

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  url:
    mail-server: ${mail-server:http://wdapi.hnlat.cc/mail-server}
    fs-server: ${fs-server:http://cloud.hnlat.cc/fs-server}
    uo-server: ${uo-server:http://192.168.1.104:10021}
    pdfsearch-server: ${pdfsearch-server:http://cloud.hnlat.cc/pdfsearch-server}
######################################################################

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    properties:
      hibernate:
        # 格式化sql日志
        format_sql: true
        # 是否显示sql注释
        # use_sql_comments: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${db.host:192.168.1.36}:${db.port:3306}/${spring.application.name}-test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${db.user:test}
    password: ${db.pass:test123}
    druid:
      # 配置初始化大小、最小、最大
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: "select 1"
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置获取连接等待超时的时间
      max-wait: 60000
      async-init: true
      filters: stat,wall,slf4j
      aop-patterns:
        - com.wd.cloud.docdelivery.service.*
        - com.wd.cloud.docdelivery.repository.*
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: "*"
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin@123
  freemarker:
    template-loader-path: ["file:/home/cloud/doc-delivery/templates/","classpath:/templates"]
    settings:
      classic_compatible: true
help:
  global:
    cloud-domain: http://cloud.hnlat.cc
    hbase-table-name: literature
    file-types: [pdf,txt,doc,docx,zip,rar,caj]
    business: doc-delivery:result
cas:
  server-url-prefix: http://sso.hnlat.cc
  server-login-url: http://sso.hnlat.cc/login
  client-host-url: http://cloud.hnlat.cc/doc-delivery
  authentication-url-patterns: /*
  logout-url-patterns: /*
  validation-url-patterns: /*
  request-wrapper-url-patterns: /*