apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-delivery
  labels:
    app: doc-delivery
    ref: __CI_ENVIRONMENT_SLUG__
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-delivery
      ref: __CI_ENVIRONMENT_SLUG__
  template:
    metadata:
      labels:
        app: doc-delivery
        ref: __CI_ENVIRONMENT_SLUG__
    spec:
      containers:
      - name: doc-delivery
        image: harbor.hnwd.com/library/doc-delivery:__VERSION__
        env:
        - name: app.port
          value: "80"
        - name: basedir
          value: /app/basedir
        - name: show-sql
          value: "false"
        - name: db.host
          value: mysql-dev.database
        - name: db.port
          value: "3306"
        - name: db.user
          value: root
        - name: db.pass
          value: wdkj@123#
        - name: mail-server
          value: http://wdapi.hnlat.com/mail-server
        - name: fs-server
          value: http://cloud.hnlat.com/fs-server
        - name: uo-server
          value: http://cloud.hnlat.com/uo-server
        - name: pdfsearch-server
          value: http://cloud.hnlat.com/pdfsearch-server
        - name: cas.server.url.prefix
          value: http://sso.hnlat.com
        - name: cas.server.login.url
          value: http://sso.hnlat.com/login
        - name: cas.client.host.url
          value: http://wdapi.hnlat.com/doc-delivery
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10

