apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-delivery
  labels:
    app: doc-delivery
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-delivery
  template:
    metadata:
      labels:
        app: doc-delivery
    spec:
      containers:
        - name: doc-delivery
          image: harbor.hnwd.com/library/doc-delivery:__VERSION__
          imagePullPolicy: Always
          env:
          - name: serverPort
            value: "80"
          - name: serverTomcatBasedir
            value: "/app/spring-tomcat"
          - name: swaggerEnable
            value: "true"
          - name: swaggerHost
            value: "cloud.hnlat.local/doc-delivery"
          - name: springJpaShowSql
            value: "false"
          - name: springJpaHibernateDDLAuto
            value: "update"
          - name: dbUrl
            value: "mysql-dev.database:3306"
          - name: dbUser
            value: "root"
          - name: dbPass
            value: "wdkj@123#"
          - name: feignUrlMaiServer
            value: "http://mail-server"
          - name: feignUrlFsServer
            value: "http://cloud.hnlat.local/fs-server"
          - name: feignUrlUoServer
            value: "http://uo-server"
          - name: feignUrlPdfsearchServer
            value: "http://cloud.hnlat.local/pdfsearch-server"
          - name: casServerUrlPrefix
            value: "http://sso.hnlat.com"
          - name: casServerLoginUrl
            value: "http://sso.hnlat.com/login"
          - name: casServerValidationUrl
            value: "http://sso"
          - name: casClientHostUrl
            value: "http://cloud.hnlat.com/doc-delivery"
          ports:
          - containerPort: 80
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 10

