apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-delivery
  labels:
    app: doc-delivery
    ref: __CI_ENVIRONMENT_SLUG__
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-delivery
      ref: __CI_ENVIRONMENT_SLUG__
  template:
    metadata:
      labels:
        app: doc-delivery
        ref: __CI_ENVIRONMENT_SLUG__
    spec:
      containers:
      - name: doc-delivery
        image: harbor.hnwd.com/library/doc-delivery:__VERSION__
        env:
        - name: serverPort
          value: "80"
        - name: serverTomcatBasedir
          value: /app/spring-tomcat
        - name: swaggerEnable
          value: "true"
        - name: swaggerHost
          value: cloud.hnlat.cc/doc-delivery
        - name: springJpaShowSql
          value: "false"
        - name: springJpaHibernateDDLAuto
          value: update
        - name: dbHost
          value: mysql-dev.database
        - name: dbPort
          value: "3306"
        - name: dbUser
          value: root
        - name: dbPass
          value: wdkj@123#
        - name: feignUrlMaiServer
          value: http://cloud.hnlat.com/mail-server
        - name: feignUrlFsServer
          value: http://cloud.hnlat.com/fs-server
        - name: feignUrlUoServer
          value: http://cloud.hnlat.com/uo-server
        - name: feignUrlPdfsearchServer
          value: http://cloud.hnlat.com/pdfsearch-server
        - name: casServerUrlPrefix
          value: http://sso.hnlat.com
        - name: casServerLoginUrl
          value: http://sso.hnlat.com/login
        - name: casClientHostUrl
          value: http://wdapi.hnlat.com/doc-delivery
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10

